-- =====================================================================================
--  CGE ARSTM — Script de sécurité (version du site : evo36)
--  À lancer UNE fois dans Supabase > SQL Editor (il peut être relancé sans danger).
--
--  Ce que fait ce script :
--   1. Crée les tables / colonnes manquantes (sans rien supprimer).
--   2. Déplace les mots de passe dans un espace privé, invisible depuis le site :
--      les mots de passe actuels continuent de fonctionner (ils sont convertis en bcrypt
--      à la première connexion). Une copie de sauvegarde est gardée dans app_private.
--   3. Crée les fonctions serveur cge_* utilisées par le site : connexion, sessions,
--      enregistrements, suppressions, J'aime, historique. Chaque fonction vérifie
--      la session et les droits (admin / secrétariat / membre) AVANT d'agir.
--   4. Ferme l'accès direct aux tables : les visiteurs ne peuvent plus que LIRE les
--      rubriques publiques (actualités publiques, activités, médiathèque, contact,
--      bureau sans matricule). Plus aucune écriture directe n'est possible.
--
--  IMPORTANT : ne relancez plus l'ancien script supabase_tout_cge_arstm.sql après celui-ci,
--  il rouvrirait les accès. Mettez en ligne le fichier du site evo36 en même temps.
-- =====================================================================================

begin;

-- ---------------------------------------------------------------------------
-- 0. Extension de chiffrement et espace privé
-- ---------------------------------------------------------------------------
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

create schema if not exists app_private;
revoke all on schema app_private from public;
do $do$ begin
  if exists (select 1 from pg_roles where rolname = 'anon') then execute 'revoke all on schema app_private from anon'; end if;
  if exists (select 1 from pg_roles where rolname = 'authenticated') then execute 'revoke all on schema app_private from authenticated'; end if;
end $do$;

-- Petites fonctions de chiffrement (écrites pour fonctionner quel que soit le schéma de pgcrypto)
do $do$
declare s text;
begin
  select n.nspname into s from pg_extension e join pg_namespace n on n.oid = e.extnamespace where e.extname = 'pgcrypto';
  execute format($f$create or replace function app_private.sha256_hex(p text) returns text
    language sql immutable set search_path = '' as $b$ select encode(%I.digest(p, 'sha256'), 'hex') $b$$f$, s);
  execute format($f$create or replace function app_private.bcrypt_hash(p text) returns text
    language sql volatile set search_path = '' as $b$ select %I.crypt(p, %I.gen_salt('bf', 10)) $b$$f$, s, s);
  execute format($f$create or replace function app_private.bcrypt_check(p text, h text) returns boolean
    language sql stable set search_path = '' as $b$ select %I.crypt(p, h) = h $b$$f$, s);
  execute format($f$create or replace function app_private.random_token() returns text
    language sql volatile set search_path = '' as $b$ select encode(%I.gen_random_bytes(32), 'hex') $b$$f$, s);
end $do$;

-- ---------------------------------------------------------------------------
-- 1. Tables et colonnes du site (créées seulement si elles manquent)
-- ---------------------------------------------------------------------------
create table if not exists public.bureau_members (
  id bigint generated by default as identity primary key,
  matricule text, pin_hash text, name text not null, role text, department text, position text, bio text, image text
);
alter table public.bureau_members add column if not exists name text;
alter table public.bureau_members add column if not exists role text;
alter table public.bureau_members add column if not exists matricule text;
alter table public.bureau_members add column if not exists pin_hash text;
alter table public.bureau_members add column if not exists department text;
alter table public.bureau_members add column if not exists position text;
alter table public.bureau_members add column if not exists bio text;
alter table public.bureau_members add column if not exists image text;

create table if not exists public.member_registry (
  id bigint generated by default as identity primary key,
  matricule text not null, name text not null, role text default 'Membre', pin_hash text
);
alter table public.member_registry add column if not exists pin_hash text;
alter table public.member_registry add column if not exists role text default 'Membre';

create table if not exists public.news (
  id bigint generated by default as identity primary key,
  title text, date text, content text, visibility text default 'public', link text, link_label text
);
alter table public.news add column if not exists visibility text default 'public';
alter table public.news add column if not exists link text;
alter table public.news add column if not exists link_label text;

create table if not exists public.jobs (
  id bigint generated by default as identity primary key,
  title text, company text, type text, description text
);
alter table public.jobs add column if not exists apply_link text;   -- nouveau : lien ou email pour postuler

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  title text, date text, description text, link text, link_label text
);
alter table public.events add column if not exists link text;
alter table public.events add column if not exists link_label text;

create table if not exists public.alumni (
  id bigint generated by default as identity primary key,
  name text, promo text, role text, company text, matricule text
);

create table if not exists public.registre (
  id bigint generated by default as identity primary key,
  image text, name text, section text, promo text, status text default 'Membre actuel', poste text
);

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  label text, value text
);

create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  title text, category text, image text
);

create table if not exists public.news_likes (
  id bigint generated by default as identity primary key,
  news_id bigint not null, user_key text not null
);

create table if not exists public.activity_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor_login text, actor_name text, action text, rubrique text, details text
);
alter table public.activity_log add column if not exists created_at timestamptz not null default now();

-- ---------------------------------------------------------------------------
-- 2. Données privées : comptes, mots de passe, sessions, tentatives
-- ---------------------------------------------------------------------------
-- Comptes administrateurs et secrétariat (avant : écrits en clair dans le fichier du site)
create table if not exists app_private.staff_accounts (
  login text primary key,                 -- ex. ARSTM-BUR-07
  name text not null,
  role text not null check (role in ('admin', 'secretariat')),
  pass_hash text not null,                -- bcrypt, ou ancienne empreinte SHA-256 si legacy_id est rempli
  legacy_id text
);

-- Mots de passe des membres (clé = matricule en majuscules)
create table if not exists app_private.credentials (
  matricule_key text primary key,
  pass_hash text not null,
  legacy_id text,                         -- matricule exact utilisé par l'ancien calcul SHA-256
  updated_at timestamptz not null default now()
);

create table if not exists app_private.sessions (
  token_hash text primary key,            -- empreinte du jeton : le jeton lui-même n'est jamais stocké
  role text not null check (role in ('admin', 'secretariat', 'member')),
  login text not null,
  name text not null,
  matricule text,
  member_role text,
  is_president boolean not null default false,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);
create index if not exists sessions_login_idx on app_private.sessions (login);

create table if not exists app_private.login_failures (
  login_key text primary key,
  failures int not null default 0,
  locked_until timestamptz,
  updated_at timestamptz not null default now()
);

-- Sauvegarde des anciennes empreintes avant de les retirer des tables publiques
create table if not exists app_private.backup_pin_hash_evo35 (
  source text not null, row_id text not null, matricule text, pin_hash text not null,
  saved_at timestamptz not null default now(),
  primary key (source, row_id)
);

alter table app_private.staff_accounts enable row level security;
alter table app_private.credentials enable row level security;
alter table app_private.sessions enable row level security;
alter table app_private.login_failures enable row level security;
alter table app_private.backup_pin_hash_evo35 enable row level security;

-- Comptes existants (mêmes mots de passe qu'avant ; convertis en bcrypt à la première connexion)
insert into app_private.staff_accounts (login, name, role, pass_hash, legacy_id) values
  ('ARSTM-BUR-07', 'Administrateur principal', 'admin',       '2506fda50c10c787058c9b0d52cf9503fa50e4ddc83624910725e08224371ad2', 'ARSTM-BUR-07'),
  ('ARSTM-BUR-12', 'Administrateur adjoint',   'admin',       'ffac76402ec97103233eb4f3ec11b51688eaeb3801ea187b5bc6852bb2d744b0', 'ARSTM-BUR-12'),
  ('ARSTM-BUR-13', 'Administrateur adjoint',   'admin',       '5a12bb9288b04d2478f7e8b6270a4e2cb298597fb65f6a69816022495ef37529', 'ARSTM-BUR-13'),
  ('ARSTM-SEC-01', 'Secrétariat',              'secretariat', '1f0317e0d0d46363279484fb37a5ad6c7b658ed49bd7797d8867c1b402cd294b', 'ARSTM-SEC-01')
on conflict (login) do nothing;

-- Migration des mots de passe membres. Priorité au bureau, comme l'ancienne connexion du site.
insert into app_private.backup_pin_hash_evo35 (source, row_id, matricule, pin_hash)
  select 'bureau_members', id::text, matricule, pin_hash from public.bureau_members where coalesce(pin_hash, '') <> ''
  on conflict do nothing;
insert into app_private.backup_pin_hash_evo35 (source, row_id, matricule, pin_hash)
  select 'member_registry', id::text, matricule, pin_hash from public.member_registry where coalesce(pin_hash, '') <> ''
  on conflict do nothing;

insert into app_private.credentials (matricule_key, pass_hash, legacy_id)
  select distinct on (upper(btrim(matricule))) upper(btrim(matricule)), lower(pin_hash), matricule
  from public.bureau_members
  where coalesce(btrim(matricule), '') <> '' and coalesce(pin_hash, '') <> ''
  order by upper(btrim(matricule)), id
on conflict (matricule_key) do nothing;
insert into app_private.credentials (matricule_key, pass_hash, legacy_id)
  select distinct on (upper(btrim(matricule))) upper(btrim(matricule)), lower(pin_hash), matricule
  from public.member_registry
  where coalesce(btrim(matricule), '') <> '' and coalesce(pin_hash, '') <> ''
  order by upper(btrim(matricule)), id
on conflict (matricule_key) do nothing;

-- Les empreintes ne restent plus dans les tables publiques (copie sauvegardée ci-dessus)
update public.bureau_members set pin_hash = null where pin_hash is not null;
update public.member_registry set pin_hash = null where pin_hash is not null;

-- ---------------------------------------------------------------------------
-- 3. Fonctions internes
-- ---------------------------------------------------------------------------
create or replace function app_private.password_matches(p_secret text, p_hash text, p_legacy_id text)
returns boolean language plpgsql stable set search_path = '' as $$
begin
  if p_hash is null or p_secret is null then return false; end if;
  if p_legacy_id is not null then
    -- ancien format du site evo35 : SHA-256 de "cge-arstm-2026|<matricule>|<mot de passe>"
    return p_hash = app_private.sha256_hex('cge-arstm-2026|' || p_legacy_id || '|' || p_secret);
  end if;
  return app_private.bcrypt_check(p_secret, p_hash);
end $$;

create or replace function app_private.check_new_password(p_new text)
returns void language plpgsql immutable set search_path = '' as $$
begin
  if p_new is null or length(btrim(p_new)) < 8 then
    raise exception 'Le mot de passe doit contenir au moins 8 caractères.' using errcode = '22023';
  end if;
  if octet_length(p_new) > 72 then
    raise exception 'Le mot de passe est trop long (72 caractères maximum).' using errcode = '22023';
  end if;
end $$;

create or replace function app_private.session_for(p_token text, p_roles text[] default null)
returns app_private.sessions language plpgsql set search_path = '' as $$
declare s app_private.sessions;
begin
  if p_token is null or p_token !~ '^[0-9a-f]{64}$' then
    raise exception 'Session invalide ou expirée.' using errcode = '28000';
  end if;
  select * into s from app_private.sessions
   where token_hash = app_private.sha256_hex(p_token) and expires_at > now();
  if not found then
    raise exception 'Session invalide ou expirée.' using errcode = '28000';
  end if;
  if p_roles is not null and not (s.role = any (p_roles)) then
    raise exception 'Action non autorisée pour votre compte.' using errcode = '42501';
  end if;
  return s;
end $$;

create or replace function app_private.session_json(s app_private.sessions)
returns jsonb language sql stable set search_path = '' as $$
  select jsonb_build_object('role', s.role, 'login', s.login, 'name', s.name, 'matricule', s.matricule,
                            'member_role', s.member_role, 'is_president', s.is_president, 'expires_at', s.expires_at);
$$;

-- Clé « J'aime » identique à l'ancienne version du site (les J'aime existants sont conservés)
create or replace function app_private.like_key(s app_private.sessions)
returns text language sql stable set search_path = '' as $$
  select app_private.sha256_hex('cge-arstm-2026|like|' || lower(coalesce(s.matricule, s.login, s.name)));
$$;

create or replace function app_private.log(s app_private.sessions, p_action text, p_rubrique text, p_details text)
returns void language plpgsql set search_path = '' as $$
begin
  if s.role = 'member' then return; end if;   -- seuls les admins et le secrétariat sont journalisés
  insert into public.activity_log (actor_login, actor_name, action, rubrique, details)
  values (s.login, s.name, p_action, coalesce(p_rubrique, ''), left(coalesce(p_details, ''), 2000));
end $$;

-- Règles par rubrique : colonnes modifiables, rôles autorisés, nom affiché dans l'historique
create or replace function app_private.table_rules(p_table text, out cols text[], out roles text[], out rubrique text, out required text[])
language plpgsql immutable set search_path = '' as $$
begin
  case p_table
    when 'news' then
      cols := array['visibility','title','date','content','link','link_label']; roles := array['admin'];
      rubrique := 'Actualités'; required := array['title','date','content'];
    when 'jobs' then
      cols := array['title','company','type','description','apply_link']; roles := array['admin'];
      rubrique := 'Emplois & Stages'; required := array['title','company','type'];
    when 'events' then
      cols := array['title','date','description','link','link_label']; roles := array['admin'];
      rubrique := 'Activités'; required := array['title','date'];
    when 'alumni' then
      cols := array['name','promo','role','company','matricule']; roles := array['admin'];
      rubrique := 'Alumni'; required := array['name','promo','role','company'];
    when 'registre' then
      cols := array['image','name','section','promo','status','poste']; roles := array['admin','secretariat'];
      rubrique := 'Registre'; required := array['name','section','promo','status'];
    when 'contacts' then
      cols := array['label','value']; roles := array['admin','secretariat'];
      rubrique := 'Contact'; required := array['label','value'];
    when 'gallery' then
      cols := array['title','category','image']; roles := array['admin','secretariat'];
      rubrique := 'Médiathèque'; required := array['title','category','image'];
    when 'bureau_members' then
      cols := array['matricule','name','role','department','position','bio','image']; roles := array['admin'];
      rubrique := 'Membres du bureau'; required := array['name','role','department'];
    else
      raise exception 'Rubrique inconnue : %', p_table using errcode = '22023';
  end case;
end $$;

-- Contrôle du contenu envoyé (longueurs, liens, photos, valeurs autorisées)
create or replace function app_private.validate_payload(p_table text, p_data jsonb, p_is_insert boolean)
returns void language plpgsql immutable set search_path = '' as $$
declare
  r record; v text; k text;
  rules record;
begin
  select * into rules from app_private.table_rules(p_table);
  foreach k in array rules.required loop
    if (p_is_insert or p_data ? k) and coalesce(btrim(p_data ->> k), '') = '' then
      raise exception 'Le champ « % » est obligatoire.', k using errcode = '22023';
    end if;
  end loop;
  for r in select key, value from jsonb_each(p_data) loop
    if jsonb_typeof(r.value) not in ('string', 'null', 'number') then
      raise exception 'Valeur invalide pour « % ».', r.key using errcode = '22023';
    end if;
    v := r.value #>> '{}';
    continue when v is null or v = '';
    if r.key = 'image' then
      if length(v) > 1500000 then
        raise exception 'La photo est trop lourde (1 Mo maximum après compression).' using errcode = '22023';
      end if;
      if v !~ '^data:image/(jpeg|png|webp|gif);base64,[A-Za-z0-9+/=]+$' and v !~* '^https?://[^\s"<>]+$' then
        raise exception 'Format de photo non accepté.' using errcode = '22023';
      end if;
    elsif r.key in ('content', 'description', 'bio') then
      if length(v) > 10000 then raise exception 'Le texte « % » est trop long (10 000 caractères maximum).', r.key using errcode = '22023'; end if;
    elsif length(v) > 500 then
      raise exception 'Le champ « % » est trop long (500 caractères maximum).', r.key using errcode = '22023';
    end if;
    -- lien web : https:// + vrai nom de domaine (ex. www.exemple.ci), sans espace
    if r.key = 'link' and v !~* '^https?://([a-z0-9-]+\.)+[a-z0-9-]{2,}(:[0-9]{1,5})?([/?#][^\s"<>]*)?$' then
      raise exception 'Le lien n''est pas une adresse web valide (exemple : https://www.exemple.ci).' using errcode = '22023';
    end if;
    if r.key = 'apply_link' and v !~* '^https?://([a-z0-9-]+\.)+[a-z0-9-]{2,}(:[0-9]{1,5})?([/?#][^\s"<>]*)?$'
                           and v !~ '^[^\s@<>"]+@[^\s@<>"]+\.[^\s@<>"]+$' then
      raise exception 'Pour postuler, indiquez un lien https:// ou une adresse email.' using errcode = '22023';
    end if;
    if r.key = 'visibility' and v not in ('public', 'membres') then
      raise exception 'Visibilité inconnue.' using errcode = '22023';
    end if;
    if p_table = 'registre' and r.key = 'status' and v not in ('Membre actuel', 'Ancien membre') then
      raise exception 'Statut inconnu.' using errcode = '22023';
    end if;
    if p_table = 'bureau_members' and r.key = 'position' and v not in ('chef', 'adjoint') then
      raise exception 'Position inconnue (chef ou adjoint).' using errcode = '22023';
    end if;
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- 4. Fonctions appelées par le site (RPC)
-- ---------------------------------------------------------------------------

-- Connexion : renvoie un jeton de session valable 12 heures
create or replace function public.cge_login(p_login text, p_secret text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  v_key text := upper(btrim(coalesce(p_login, '')));
  v_secret text := coalesce(p_secret, '');
  v_max constant int := 5;
  v_fail app_private.login_failures;
  v_staff app_private.staff_accounts;
  v_cred app_private.credentials;
  v_ok boolean := false;
  v_is_staff boolean := false;
  v_name text; v_matricule text; v_member_role text; v_pres boolean := false;
  v_token text;
  s app_private.sessions;
begin
  if v_key = '' or v_secret = '' or length(v_key) > 64 or length(v_secret) > 200 then
    return jsonb_build_object('ok', false, 'reason', 'invalid');
  end if;

  delete from app_private.sessions where expires_at < now();
  delete from app_private.login_failures
   where updated_at < now() - interval '1 day' and (locked_until is null or locked_until < now());

  select * into v_fail from app_private.login_failures where login_key = v_key for update;
  if found and v_fail.locked_until is not null and v_fail.locked_until > now() then
    return jsonb_build_object('ok', false, 'reason', 'locked',
      'retry_after_minutes', greatest(1, ceil(extract(epoch from (v_fail.locked_until - now())) / 60))::int);
  end if;

  select * into v_staff from app_private.staff_accounts where upper(login) = v_key;
  if found then
    v_is_staff := true;
    v_ok := app_private.password_matches(v_secret, v_staff.pass_hash, v_staff.legacy_id);
    if v_ok and v_staff.legacy_id is not null then
      update app_private.staff_accounts set pass_hash = app_private.bcrypt_hash(v_secret), legacy_id = null where login = v_staff.login;
    end if;
  else
    select * into v_cred from app_private.credentials where matricule_key = v_key;
    if found then
      v_ok := app_private.password_matches(v_secret, v_cred.pass_hash, v_cred.legacy_id);
      if v_ok then
        select r.name, coalesce(nullif(r.role, ''), 'Membre'), r.matricule into v_name, v_member_role, v_matricule
          from public.member_registry r where upper(btrim(r.matricule)) = v_key order by r.id limit 1;
        if v_name is null then
          select b.name, b.role, b.matricule into v_name, v_member_role, v_matricule
            from public.bureau_members b where upper(btrim(b.matricule)) = v_key order by b.id limit 1;
        end if;
        if v_name is null then
          v_ok := false;   -- matricule retiré de l'annuaire et du bureau : plus de connexion
        else
          select exists (select 1 from public.bureau_members b
                          where upper(btrim(b.matricule)) = v_key and b.department = 'presidence'
                            and coalesce(b.position, 'chef') = 'chef') into v_pres;
          if v_cred.legacy_id is not null then
            update app_private.credentials set pass_hash = app_private.bcrypt_hash(v_secret), legacy_id = null, updated_at = now()
             where matricule_key = v_key;
          end if;
        end if;
      end if;
    else
      perform app_private.bcrypt_hash(v_secret);   -- même durée de réponse qu'un vrai contrôle
    end if;
  end if;

  if not v_ok then
    insert into app_private.login_failures as f (login_key, failures, locked_until, updated_at)
    values (v_key, 1, null, now())
    on conflict (login_key) do update set
      failures = case when f.locked_until is not null and f.locked_until <= now() then 1 else f.failures + 1 end,
      locked_until = null,
      updated_at = now()
    returning * into v_fail;
    if v_fail.failures >= v_max then
      update app_private.login_failures set locked_until = now() + interval '15 minutes'
       where login_key = v_key returning * into v_fail;
    end if;
    if v_is_staff then
      insert into public.activity_log (actor_login, actor_name, action, rubrique, details)
      values (v_staff.login, v_staff.name, 'Échec de connexion', '', 'Mot de passe incorrect');
    end if;
    if v_fail.locked_until is not null then
      return jsonb_build_object('ok', false, 'reason', 'locked', 'retry_after_minutes', 15);
    end if;
    return jsonb_build_object('ok', false, 'reason', 'invalid', 'remaining', v_max - v_fail.failures);
  end if;

  delete from app_private.login_failures where login_key = v_key;
  v_token := app_private.random_token();
  if v_is_staff then
    insert into app_private.sessions (token_hash, role, login, name, matricule, member_role, is_president, expires_at)
    values (app_private.sha256_hex(v_token), v_staff.role, v_staff.login, v_staff.name, v_staff.login, null, false, now() + interval '12 hours')
    returning * into s;
    perform app_private.log(s, 'Connexion', '', 'Connexion au site');
  else
    insert into app_private.sessions (token_hash, role, login, name, matricule, member_role, is_president, expires_at)
    values (app_private.sha256_hex(v_token), 'member', v_key, v_name, v_matricule, v_member_role, v_pres, now() + interval '12 hours')
    returning * into s;
  end if;
  return jsonb_build_object('ok', true, 'token', v_token, 'session', app_private.session_json(s));
end $$;

-- Reprise de session après un rechargement de la page (null si expirée)
create or replace function public.cge_session(p_token text)
returns jsonb language sql security definer set search_path = '' as $$
  select app_private.session_json(s) from app_private.sessions s
   where s.token_hash = app_private.sha256_hex(coalesce(p_token, '')) and s.expires_at > now();
$$;

create or replace function public.cge_logout(p_token text)
returns void language plpgsql security definer set search_path = '' as $$
declare s app_private.sessions;
begin
  delete from app_private.sessions where token_hash = app_private.sha256_hex(coalesce(p_token, '')) returning * into s;
  if s.token_hash is not null then perform app_private.log(s, 'Déconnexion', '', 'Déconnexion du site'); end if;
end $$;

-- Changement de son propre mot de passe (membres, admins, secrétariat)
create or replace function public.cge_change_password(p_token text, p_current text, p_new text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  s app_private.sessions := app_private.session_for(p_token);
  v_staff app_private.staff_accounts;
  v_cred app_private.credentials;
begin
  perform app_private.check_new_password(p_new);
  if s.role in ('admin', 'secretariat') then
    select * into v_staff from app_private.staff_accounts where login = s.login for update;
    if not found or not app_private.password_matches(coalesce(p_current, ''), v_staff.pass_hash, v_staff.legacy_id) then
      raise exception 'Le mot de passe actuel est incorrect.' using errcode = '22023';
    end if;
    update app_private.staff_accounts set pass_hash = app_private.bcrypt_hash(p_new), legacy_id = null where login = s.login;
  else
    select * into v_cred from app_private.credentials where matricule_key = s.login for update;
    if not found or not app_private.password_matches(coalesce(p_current, ''), v_cred.pass_hash, v_cred.legacy_id) then
      raise exception 'Le mot de passe actuel est incorrect.' using errcode = '22023';
    end if;
    update app_private.credentials set pass_hash = app_private.bcrypt_hash(p_new), legacy_id = null, updated_at = now()
     where matricule_key = s.login;
  end if;
  -- déconnecte les autres appareils de la même personne
  delete from app_private.sessions where login = s.login and token_hash <> s.token_hash;
  perform app_private.log(s, 'Changement de mot de passe', 'Comptes', s.name || ' (' || s.login || ')');
end $$;

-- Mot de passe provisoire défini par un admin (premier mot de passe ou oubli)
create or replace function public.cge_admin_set_password(p_token text, p_matricule text, p_new text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  s app_private.sessions := app_private.session_for(p_token, array['admin']);
  v_key text := upper(btrim(coalesce(p_matricule, '')));
  v_name text;
begin
  perform app_private.check_new_password(p_new);
  select name into v_name from public.member_registry where upper(btrim(matricule)) = v_key order by id limit 1;
  if v_name is null then
    select name into v_name from public.bureau_members where upper(btrim(matricule)) = v_key order by id limit 1;
  end if;
  if v_name is null then
    raise exception 'Matricule introuvable dans l''annuaire ou le bureau.' using errcode = 'P0002';
  end if;
  insert into app_private.credentials (matricule_key, pass_hash, legacy_id, updated_at)
  values (v_key, app_private.bcrypt_hash(p_new), null, now())
  on conflict (matricule_key) do update set pass_hash = excluded.pass_hash, legacy_id = null, updated_at = now();
  delete from app_private.login_failures where login_key = v_key;
  delete from app_private.sessions where role = 'member' and login = v_key;
  perform app_private.log(s, 'Réinitialisation mot de passe', 'Comptes membres', v_name || ' (' || v_key || ')');
end $$;

-- Liste des comptes de connexion (espace admin)
create or replace function public.cge_admin_accounts(p_token text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare s app_private.sessions := app_private.session_for(p_token, array['admin']);
begin
  return (
    with ids as (
      select upper(btrim(matricule)) as k, btrim(matricule) as matricule, name, coalesce(nullif(role, ''), 'Membre') as role, 0 as prio
        from public.member_registry where coalesce(btrim(matricule), '') <> ''
      union all
      select upper(btrim(matricule)), btrim(matricule), name, role, 1
        from public.bureau_members where coalesce(btrim(matricule), '') <> ''
    ), d as (
      select distinct on (k) * from ids order by k, prio
    )
    select coalesce(jsonb_agg(jsonb_build_object(
             'matricule', d.matricule, 'name', d.name, 'role', d.role,
             'has_password', c.matricule_key is not null,
             'locked', coalesce(f.locked_until > now(), false)) order by d.k), '[]'::jsonb)
      from d
      left join app_private.credentials c on c.matricule_key = d.k
      left join app_private.login_failures f on f.login_key = d.k
  );
end $$;

-- Création d'un compte membre dans l'annuaire (espace admin)
create or replace function public.cge_admin_add_account(p_token text, p_matricule text, p_name text, p_password text)
returns void language plpgsql security definer set search_path = '' as $$
declare
  s app_private.sessions := app_private.session_for(p_token, array['admin']);
  v_key text := upper(btrim(coalesce(p_matricule, '')));
  v_name text := btrim(coalesce(p_name, ''));
begin
  if v_key !~ '^[A-Z0-9][A-Z0-9._/-]{1,39}$' then
    raise exception 'Matricule invalide (lettres, chiffres et tirets, 40 caractères maximum).' using errcode = '22023';
  end if;
  if length(v_name) < 2 or length(v_name) > 120 then
    raise exception 'Le nom doit contenir entre 2 et 120 caractères.' using errcode = '22023';
  end if;
  if exists (select 1 from public.member_registry where upper(btrim(matricule)) = v_key) then
    raise exception 'Ce matricule existe déjà dans l''annuaire.' using errcode = '22023';
  end if;
  if coalesce(p_password, '') <> '' then perform app_private.check_new_password(p_password); end if;
  insert into public.member_registry (matricule, name, role) values (v_key, v_name, 'Membre');
  if coalesce(p_password, '') <> '' then
    insert into app_private.credentials (matricule_key, pass_hash, legacy_id, updated_at)
    values (v_key, app_private.bcrypt_hash(p_password), null, now())
    on conflict (matricule_key) do update set pass_hash = excluded.pass_hash, legacy_id = null, updated_at = now();
  end if;
  perform app_private.log(s, 'Création de compte', 'Comptes membres', v_name || ' (' || v_key || ')');
end $$;

-- Lectures réservées : rubriques membres (toute session) et données admin
create or replace function public.cge_list(p_token text, p_kind text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare s app_private.sessions;
begin
  if p_kind in ('bureau_matricules', 'activity_log') then
    s := app_private.session_for(p_token, array['admin']);
  else
    s := app_private.session_for(p_token);
  end if;
  case p_kind
    when 'registre' then
      return (select coalesce(jsonb_agg(to_jsonb(t) order by t.name), '[]'::jsonb) from public.registre t);
    when 'alumni' then
      return (select coalesce(jsonb_agg(to_jsonb(t) order by t.id), '[]'::jsonb) from public.alumni t);
    when 'jobs' then
      return (select coalesce(jsonb_agg(to_jsonb(t) order by t.id), '[]'::jsonb) from public.jobs t);
    when 'news_membres' then
      return (select coalesce(jsonb_agg(to_jsonb(t) order by t.id), '[]'::jsonb) from public.news t where t.visibility = 'membres');
    when 'bureau_matricules' then
      return (select coalesce(jsonb_agg(jsonb_build_object('id', t.id, 'matricule', t.matricule) order by t.id), '[]'::jsonb)
                from public.bureau_members t);
    when 'activity_log' then
      return (select coalesce(jsonb_agg(to_jsonb(t) order by t.created_at desc), '[]'::jsonb)
                from (select * from public.activity_log order by created_at desc limit 1000) t);
    else
      raise exception 'Liste inconnue : %', p_kind using errcode = '22023';
  end case;
end $$;

-- Ajout (p_id vide) ou modification d'une fiche, avec contrôle des droits et historique
create or replace function public.cge_save(p_token text, p_table text, p_id text, p_data jsonb, p_details text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  rules record;
  s app_private.sessions;
  v_data jsonb;
  v_list text;
  v_row jsonb;
  v_old jsonb;
  v_action text;
begin
  select * into rules from app_private.table_rules(p_table);
  s := app_private.session_for(p_token, rules.roles);
  if p_data is null or jsonb_typeof(p_data) <> 'object' then
    raise exception 'Données manquantes.' using errcode = '22023';
  end if;
  -- seules les colonnes prévues pour cette rubrique sont prises en compte
  select coalesce(jsonb_object_agg(key, value), '{}'::jsonb) into v_data
    from jsonb_each(p_data) where key = any (rules.cols);
  if v_data = '{}'::jsonb then
    raise exception 'Aucune donnée à enregistrer.' using errcode = '22023';
  end if;
  perform app_private.validate_payload(p_table, v_data, coalesce(p_id, '') = '');
  select string_agg(format('%I', k), ', ') into v_list from jsonb_object_keys(v_data) as k;

  if coalesce(p_id, '') = '' then
    execute format('insert into public.%I as t (%s) select %s from jsonb_populate_record(null::public.%I, $1) returning to_jsonb(t.*)',
                   p_table, v_list, v_list, p_table)
      using v_data into v_row;
    v_action := 'Ajout';
  else
    execute format('select to_jsonb(t) from public.%I t where t.id::text = $1', p_table) using p_id into v_old;
    if v_old is null then
      raise exception 'Cette fiche n''existe plus (elle a peut-être été supprimée entre-temps).' using errcode = 'P0002';
    end if;
    execute format('update public.%I as t set (%s) = (select %s from jsonb_populate_record(null::public.%I, $1)) where t.id::text = $2 returning to_jsonb(t.*)',
                   p_table, v_list, v_list, p_table)
      using v_data, p_id into v_row;
    v_action := 'Modification';
  end if;

  v_row := v_row - 'pin_hash';
  perform app_private.log(s, v_action, rules.rubrique,
    coalesce(nullif(btrim(p_details), ''), v_row ->> 'title', v_row ->> 'name', v_row ->> 'label', ''));
  return v_row;
end $$;

create or replace function public.cge_delete(p_token text, p_table text, p_id text, p_details text default null)
returns void language plpgsql security definer set search_path = '' as $$
declare
  rules record;
  s app_private.sessions;
  v_old jsonb;
begin
  select * into rules from app_private.table_rules(p_table);
  s := app_private.session_for(p_token, rules.roles);
  if p_table = 'news' then
    delete from public.news_likes where news_id::text = p_id;   -- les J'aime de l'actualité partent avec elle
  end if;
  execute format('delete from public.%I t where t.id::text = $1 returning to_jsonb(t)', p_table) using p_id into v_old;
  if v_old is null then
    raise exception 'Cette fiche n''existe plus (elle a peut-être déjà été supprimée).' using errcode = 'P0002';
  end if;
  perform app_private.log(s, 'Suppression', rules.rubrique,
    coalesce(nullif(btrim(p_details), ''), v_old ->> 'title', v_old ->> 'name', v_old ->> 'label', ''));
end $$;

-- Compteurs de J'aime (visiteurs : actualités publiques ; connectés : toutes + « mine »)
create or replace function public.cge_likes(p_token text default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_key text;
begin
  select app_private.like_key(s) into v_key from app_private.sessions s
   where s.token_hash = app_private.sha256_hex(coalesce(p_token, '')) and s.expires_at > now();
  return (
    select coalesce(jsonb_agg(jsonb_build_object('news_id', l.news_id, 'count', l.cnt, 'mine', l.mine)), '[]'::jsonb)
      from (
        select nl.news_id, count(*) as cnt, coalesce(bool_or(nl.user_key = v_key), false) as mine
          from public.news_likes nl
         where exists (select 1 from public.news n
                        where n.id::text = nl.news_id::text
                          and (coalesce(n.visibility, 'public') = 'public' or v_key is not null))
         group by nl.news_id
      ) l
  );
end $$;

create or replace function public.cge_toggle_like(p_token text, p_news_id text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  s app_private.sessions := app_private.session_for(p_token);
  v_key text := app_private.like_key(s);
  v_liked boolean;
  v_count int;
begin
  if not exists (select 1 from public.news where id::text = p_news_id) then
    raise exception 'Actualité introuvable.' using errcode = 'P0002';
  end if;
  perform pg_advisory_xact_lock(hashtext('cge_like|' || v_key || '|' || p_news_id));
  if exists (select 1 from public.news_likes where news_id::text = p_news_id and user_key = v_key) then
    delete from public.news_likes where news_id::text = p_news_id and user_key = v_key;
    v_liked := false;
  else
    insert into public.news_likes (news_id, user_key) select n.id, v_key from public.news n where n.id::text = p_news_id;
    v_liked := true;
  end if;
  select count(*) into v_count from public.news_likes where news_id::text = p_news_id;
  return jsonb_build_object('liked', v_liked, 'count', v_count);
end $$;

-- ---------------------------------------------------------------------------
-- 5. Droits d'accès : plus aucune écriture directe, lecture publique limitée
-- ---------------------------------------------------------------------------
do $do$
declare
  t text;
  pol record;
  api_roles text := (select string_agg(quote_ident(rolname), ', ') from pg_roles where rolname in ('anon', 'authenticated'));
begin
  foreach t in array array['bureau_members','member_registry','news','jobs','events','alumni','registre','contacts','gallery','news_likes','activity_log'] loop
    execute format('alter table public.%I enable row level security', t);
    for pol in select policyname from pg_policies where schemaname = 'public' and tablename = t loop
      execute format('drop policy %I on public.%I', pol.policyname, t);
    end loop;
    execute format('revoke all on table public.%I from public', t);
    if api_roles is not null then
      execute format('revoke all on table public.%I from %s', t, api_roles);
    end if;
  end loop;

  if api_roles is not null then
    -- Lecture publique : activités, contact, médiathèque (tout), actualités (publiques seulement)
    foreach t in array array['events','contacts','gallery','news'] loop
      execute format('grant select on table public.%I to %s', t, api_roles);
    end loop;
    -- Bureau : lecture publique SANS matricule ni empreinte de mot de passe
    execute format('grant select (id, name, role, department, position, bio, image) on table public.bureau_members to %s', api_roles);

    execute format('create policy lecture_publique on public.events for select to %s using (true)', api_roles);
    execute format('create policy lecture_publique on public.contacts for select to %s using (true)', api_roles);
    execute format('create policy lecture_publique on public.gallery for select to %s using (true)', api_roles);
    execute format('create policy lecture_publique on public.bureau_members for select to %s using (true)', api_roles);
    execute format($p$create policy lecture_publique on public.news for select to %s using (coalesce(visibility, 'public') = 'public')$p$, api_roles);
  end if;
end $do$;

-- Fonctions : appelables par le site uniquement pour celles du schéma public
revoke all on all functions in schema app_private from public;
do $do$
declare
  f text;
  api_roles text := (select string_agg(quote_ident(rolname), ', ') from pg_roles where rolname in ('anon', 'authenticated'));
begin
  foreach f in array array[
    'public.cge_login(text, text)', 'public.cge_session(text)', 'public.cge_logout(text)',
    'public.cge_change_password(text, text, text)', 'public.cge_admin_set_password(text, text, text)',
    'public.cge_admin_accounts(text)', 'public.cge_admin_add_account(text, text, text, text)',
    'public.cge_list(text, text)', 'public.cge_save(text, text, text, jsonb, text)', 'public.cge_delete(text, text, text, text)',
    'public.cge_likes(text)', 'public.cge_toggle_like(text, text)'
  ] loop
    execute format('revoke all on function %s from public', f);
    if api_roles is not null then execute format('grant execute on function %s to %s', f, api_roles); end if;
  end loop;
end $do$;

commit;

-- Demande à l'API Supabase de relire la liste des fonctions
notify pgrst, 'reload schema';

-- ---------------------------------------------------------------------------
-- Vérification : ce tableau doit s'afficher en bas de l'éditeur SQL
-- ---------------------------------------------------------------------------
select 'Comptes admin / secrétariat' as element, count(*)::text as valeur from app_private.staff_accounts
union all select 'Membres avec mot de passe', count(*)::text from app_private.credentials
union all select 'Empreintes restées publiques (doit être 0)',
  ((select count(*) from public.bureau_members where pin_hash is not null) + (select count(*) from public.member_registry where pin_hash is not null))::text
union all select 'Fonctions cge_* installées', count(*)::text from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.proname like 'cge\_%';
